const languages = () => [
  'Afrikaans',
  'Akan',
  'Albanian',
  'Amharic',
  'Arabic',
  'Aragonese',
  'Armenian',
  'Assamese',
  'Avaric',
  'Avestan',
  'Aymara',
  'Azerbaijani',
  'Bambara',
  'Bashkir',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bihari languages',
  'Bislama',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Catalan',
  'Central Khmer',
  'Chamorro',
  'Chechen',
  'Chichewa',
  'Chinese',
  'Chuvash',
  'Corsican',
  'Cree',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'Dzongkha',
  'English',
  'Esperanto',
  'Estonian',
  'Ewe',
  'Faroese',
  'Fijian',
  'Finnish',
  'French',
  'Fulah',
  'Galician',
  'Ganda',
  'Georgian',
  'German',
  'Greek',
  'Greenlandic',
  'Guarani',
  'Gujarati',
  'Haitian',
  'Hausa',
  'Hebrew',
  'Herero',
  'Hindi',
  'Hiri Motu',
  'Hungarian',
  'Icelandic',
  'Ido',
  'Igbo',
  'Indonesian',
  'Interlingua',
  'Interlingue',
  'Inuktitut',
  'Inupiaq',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kalaallisut',
  'Kannada',
  'Kanuri',
  'Kashmiri',
  'Kazakh',
  'Kikuyu',
  'Kinyarwanda',
  'Kirghiz',
  'Kongo',
  'Korean',
  'Kuanyama',
  'Kurdish',
  'Lao',
  'Latin',
  'Latvian',
  'Limburgan',
  'Lingala',
  'Lithuanian',
  'Luba-Katanga',
  'Luxembourgish',
  'Macedonian',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maldivian',
  'Maltese',
  'Manx',
  'Maori',
  'Marathi',
  'Marshallese',
  'Mongolian',
  'Nauru',
  'Navajo',
  'Nepali',
  'Ndonga',
  'North Ndebele',
  'Northern Sami',
  'Norwegian',
  'Norwegian Bokmål',
  'Norwegian Nynorsk',
  'Occitan',
  'Ojibwa',
  'Oriya',
  'Oromo',
  'Ossetic',
  'Pali',
  'Panjabi',
  'Persian',
  'Polish',
  'Portuguese',
  'Pushto',
  'Quechua',
  'Romanian',
  'Romansh',
  'Rundi',
  'Russian',
  'Samoan',
  'Sardinian',
  'Scots Gaelic',
  'Serbian',
  'Serbo-Croatian',
  'Sesotho',
  'Shona',
  'Sichuan Yi',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Sotho, Southern',
  'Spanish',
  'Sundanese',
  'Swahili',
  'Swati',
  'Swedish',
  'Tagalog',
  'Tahitian',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tibetan',
  'Tigrinya',
  'Tonga',
  'Tswana',
  'Turkish',
  'Turkmen',
  'Twi',
  'Uighur',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Venda',
  'Vietnamese',
  'Volapük',
  'Walloon',
  'Welsh',
  'Western Frisian',
  'Wolof',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zhuang',
  'Zulu',
];
const availableOptions = () => ['ASAP', '1 week', '2 weeks', '3 weeks'];
const skills = () => [
  'JavaScript',
  'Python',
  'Java',
  'Ruby',
  'C#',
  'PHP',
  'HTML',
  'CSS',
  'Swift',
  'Kotlin',
  'Objective-C',
  'SQL',
  'Go',
  'C++',
  'TypeScript',
  'Rust',
  'Perl',
  'Scala',
  'Haskell',
  'Lua',
  'React',
  'Angular',
  'Vue.js',
  'Ember.js',
  'Backbone.js',
  'Sass',
  'Less',
  'jQuery',
  'Redux',
  'D3.js',
  'Three.js',
  'Bootstrap',
  'Foundation',
  'Spring Boot',
  'Django',
  'Ruby on Rails',
  'Express.js',
  'Flask',
  '.NET Core',
  'Laravel',
  'Symfony',
  'ASP.NET',
  'Node.js',
  'Dropwizard',
  'React Native',
  'Flutter',
  'Xamarin',
  'Ionic',
  'PhoneGap',
  'NativeScript',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'Travis CI',
  'Ansible',
  'Terraform',
  'Puppet',
  'Chef',
  'Vagrant',
  'Git',
  'GitLab CI/CD',
  'Selenium',
  'Appium',
  'JIRA',
  'TestRail',
  'Cypress',
  'Postman',
  'JUnit',
  'TestNG',
  'Robot Framework',
  'Mocha',
  'MySQL',
  'PostgreSQL',
  'Supabase',
  'Prisma',
  'ORM',
  'MongoDB',
  'Oracle Database',
  'SQL Server',
  'Redis',
  'Cassandra',
  'Firebase',
  'Elasticsearch',
  'Neo4j',
  'AWS',
  'Azure',
  'Google Cloud',
  'Heroku',
  'DigitalOcean',
  'IBM Cloud',
  'Alibaba Cloud',
  'Oracle Cloud',
  'Kubernetes Engine',
  'Lambda',
  'R',
  'MATLAB',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'Jupyter',
  'Tableau',
  'Power BI',
  'BigML',
  'Bitbucket',
  'Jira',
  'Confluence',
  'Slack',
  'Trello',
  'Asana',
  'Notion',
  'Figma',
  'Sketch',
  'Nmap',
  'Wireshark',
  'Metasploit',
  'Snort',
  'OpenVAS',
  'Hashcat',
  'OWASP ZAP',
  'Kali Linux',
  'Splunk',
  'Qualys',
  'CircleCI',
  'TeamCity',
  'Bamboo',
  'GitLab CI',
  'Travis CI',
  'Codeship',
  'GoCD',
  'Octopus Deploy',
  'Capistrano',
  'Jenkins X',
  'Rust',
  'Perl',
  'Scala',
  'Haskell',
  'Lua',
  'Dart',
  'Groovy',
  'Elixir',
  'Clojure',
  'COBOL',
  'F#',
  'Ada',
  'PL/SQL',
  'Swift',
  'Kotlin',
  'Objective-C',
  'Racket',
  'Scheme',
  'Matlab',
  'Julia',
  'Next.js',
  'Nuxt.js',
  'Gatsby',
  'Tailwind CSS',
  'Material-UI',
  'Ant Design',
  'Foundation',
  'Bulma',
  'Semantic UI',
  'Materialize',
  'Quasar',
  'Chakra UI',
  'Buefy',
  'Carbon Design System',
  'Vuetify',
  'Element UI',
  'Dojo Toolkit',
  'Mithril',
  'Play Framework',
  'Nest.js',
  'AdonisJS',
  'Phoenix',
  'Grails',
  'Ratpack',
  'Sinatra',
  'Hanami',
  'Sails.js',
  'LoopBack',
  'Nest.js',
  'Feathers',
  'CakePHP',
  'Slim',
  'Rocket',
  'Warp',
  'Corona SDK',
  'Sencha Touch',
  'Mobile Angular UI',
  'Kivy',
  'Codename One',
  'Nativescript-Vue',
  'Fuse',
  'Appgyver',
  'Red Hat Mobile',
  'Xojo',
  'JUCE',
  'Xamarin.Forms',
  'AppSheet',
  'Nomad',
  'Consul',
  'Spinnaker',
  'Rancher',
  'Rundeck',
  'JFrog Artifactory',
  'Harbor',
  'Packer',
  'Nomad',
  'Rook',
  'Helm',
  'Telegraf',
  'Fluentd',
  'Prometheus',
  'Grafana',
  'Zipkin',
  'Jest',
  'Enzyme',
  'Detox',
  'Gauge',
  'Watir',
  'Katalon Studio',
  'Gatling',
  'Locust',
  'Karate',
  'Geb',
  'Behat',
  'Cucumber',
  'Spock',
  'Galen',
  'SQLite',
  'MariaDB',
  'Couchbase',
  'Amazon Aurora',
  'DB2',
  'Teradata',
  'HBase',
  'CouchDB',
  'ArangoDB',
  'Riak',
  'InfluxDB',
  'Snowflake',
  'CockroachDB',
  'Amazon Redshift',
  'Memcached',
  'Hive',
  'Erlang',
  'COBOL',
  'F#',
  'Ada',
  'PL/SQL',
  'Swift',
  'Kotlin',
  'Objective-C',
  'Racket',
  'Scheme',
  'Matlab',
  'Julia',
  'Fortran',
  'Prolog',
  'Dart',
  'Rexx',
  'Verilog',
  'VHDL',
  'COOL',
  'FoxPro',
  'Tcl',
  'COOL',
  'Apex',
  'Logtalk',
  'RPG',
  'XQuery',
  'ABAP',
  'IDL',
  'Forth',
  'MUMPS',
  'PL/I',
  'Oberon',
  'Logo',
  'SAS',
  'Simula',
  'Scratch',
  'Smalltalk',
  'Eiffel',
  'COOL',
  'Oxygene',
  'R',
  'Hack',
  'Alice',
  'Dart',
  'Elm',
  'Red',
  'PowerShell',
  'Rust',
  'Julia',
  'Svelte',
  'Stencil',
  'Quasar',
  'Chakra UI',
  'Buefy',
  'Carbon Design System',
  'Vuetify',
  'Element UI',
  'Dojo Toolkit',
  'Mithril',
  'Aurelia',
  'Polymer',
  'Knockout.js',
  'Riot.js',
  'MooTools',
  'Ext JS',
  'Zurb Foundation',
  'BEM',
  'Pure.css',
  'Material Design Lite',
  'Semantic UI React',
  'Onsen UI',
  'Weex',
  'AMP (Accelerated Mobile Pages)',
  'BonsaiJS',
  'Preact',
  'Alpine.js',
  'Moon.js',
  'Stimulus',
  'SproutCore',
  'Play Framework',
  'Nest.js',
  'AdonisJS',
  'Phoenix',
  'Grails',
  'Ratpack',
  'Sinatra',
  'Hanami',
  'Sails.js',
  'LoopBack',
  'Feathers',
  'CakePHP',
  'Slim',
  'Rocket',
  'Warp',
  'Vert.x',
  'Actix',
  'Nancy',
  'Kitura',
  'Perfect',
  'Zewo',
  'Rails API',
  'Lumen',
  'Hug',
  'Buffalo',
  'Flask-RESTful',
  'Falcon',
  'Slim Framework',
  'AppSheet',
  'Unity',
  'Cocos2d',
  'Lumberyard',
  'Defold',
  'Buildbox',
  'GameMaker',
  'AppMakr',
  'GameSalad',
  'Unreal Engine',
  'Gideros',
  'Moai',
  'CryEngine',
  'Oxygine',
  'Stencyl',
  'Phaser',
  'Godot',
  'Marmalade',
  'Monogame',
  'Cordova',
];
const englishLevels = () => [
  'Basic (A0-A2)',
  'Intermediate (B1)',
  'Upper Intermediate (B2)',
  'Fluent (C1-C2)',
  'Native / Bilingual'];

const rolesArray = () => [
  {
    role: 'Frontend Developer',
    description: 'Specializes in creating user interfaces and client-side development using technologies like HTML, CSS, and JavaScript.',
  },
  {
    role: 'Backend Developer',
    description: 'Focuses on server-side development, database management, and server operations.',
  },
  {
    role: 'Full-Stack Developer',
    description: 'Proficient in both frontend and backend development, capable of working on the entire software stack.',
  },
  {
    role: 'Mobile App Developer',
    description: 'Specializes in creating applications for mobile platforms such as iOS and Android.',
  },
  {
    role: 'DevOps Engineer',
    description: 'Manages the development, deployment, and maintenance of software, focusing on automation, continuous integration, and continuous deployment (CI/CD).',
  },
  {
    role: 'Manual QA Engineer',
    description: 'Ensures the quality and functionality of software through testing and quality control processes.',
  },
  {
    role: 'QA Automation Engineer',
    description: 'Develops automated scripts and tools to streamline development and testing processes.',
  },
  {
    role: 'Software Architect',
    description: 'Designs the high-level structure of software systems, defining key components and their interactions.',
  },
  {
    role: 'UI/UX Designer',
    description: 'Focuses on creating intuitive and visually appealing user interfaces and user experiences.',
  },
  {
    role: 'Product Manager',
    description: 'Oversees the development process, defines product goals, and prioritizes features based on customer and business needs.',
  },
  {
    role: 'Scrum Master',
    description: 'Facilitates agile development processes, ensuring the team follows Scrum practices and removing obstacles.',
  },
  {
    role: 'Business Analyst',
    description: 'Analyzes business requirements and translates them into software requirements and features.',
  },
  {
    role: 'Database Administrator (DBA)',
    description: 'Manages and maintains the company\'s databases, ensuring data integrity and availability.',
  },
  {
    role: 'Systems Administrator',
    description: 'Handles server infrastructure, network configurations, and system maintenance.',
  },
  {
    role: 'Security Engineer',
    description: 'Focuses on the security of software and infrastructure, implementing security measures and conducting security audits.',
  },
  {
    role: 'Cloud Engineer',
    description: 'Manages cloud infrastructure and services, such as AWS, Azure, or Google Cloud.',
  },
  {
    role: 'Data Scientist',
    description: 'Analyzes and interprets complex data to provide insights and make data-driven decisions.',
  },
  {
    role: 'Machine Learning Engineer',
    description: 'Develops machine learning models and algorithms for data analysis and predictive purposes.',
  },
  {
    role: 'Technical Writer',
    description: 'Creates documentation, user guides, and manuals for software products.',
  },
  {
    role: 'Support Engineer',
    description: 'Provides technical support to customers, addressing their issues and inquiries.',
  },
  {
    role: 'Release Manager',
    description: 'Oversees the release process, ensuring smooth deployments and version control.',
  },
  {
    role: 'Project Manager',
    description: 'Manages software development projects, including scheduling, budgeting, and resource allocation.',
  },
  {
    role: 'Data Engineer',
    description: 'Focuses on the design and management of data pipelines and ETL processes.',
  },
  {
    role: 'Release Engineer',
    description: 'Manages the release process, including build, packaging, and deployment of software.',
  },
  {
    role: 'Site Reliability Engineer (SRE)',
    description: 'Focuses on the reliability, availability, and performance of software and systems in production.',
  },
  {
    role: 'Other Role',
    description: '',
  },
];

const countriesArray = () => [
  {
    'country': 'Afghanistan',
    'region': 'Asia',
  },
  {
    'country': 'Åland',
    'region': 'Europe',
  },
  {
    'country': 'Albania',
    'region': 'Europe',
  },
  {
    'country': 'Algeria',
    'region': 'Africa',
  },
  {
    'country': 'American Samoa',
    'region': 'Oceania',
  },
  {
    'country': 'Andorra',
    'region': 'Europe',
  },
  {
    'country': 'Angola',
    'region': 'Africa',
  },
  {
    'country': 'Anguilla',
    'region': 'North America',
  },
  {
    'country': 'Antarctica',
    'region': 'Antarctica',
  },
  {
    'country': 'Antigua and Barbuda',
    'region': 'North America',
  },
  {
    'country': 'Argentina',
    'region': 'South America',
  },
  {
    'country': 'Armenia',
    'region': 'Asia',
  },
  {
    'country': 'Aruba',
    'region': 'North America',
  },
  {
    'country': 'Australia',
    'region': 'Oceania',
  },
  {
    'country': 'Austria',
    'region': 'Europe',
  },
  {
    'country': 'Azerbaijan',
    'region': 'Asia',
  },
  {
    'country': 'Bahamas',
    'region': 'North America',
  },
  {
    'country': 'Bahrain',
    'region': 'Asia',
  },
  {
    'country': 'Bangladesh',
    'region': 'Asia',
  },
  {
    'country': 'Barbados',
    'region': 'North America',
  },
  {
    'country': 'Belarus',
    'region': 'Europe',
  },
  {
    'country': 'Belgium',
    'region': 'Europe',
  },
  {
    'country': 'Belize',
    'region': 'North America',
  },
  {
    'country': 'Benin',
    'region': 'Africa',
  },
  {
    'country': 'Bermuda',
    'region': 'North America',
  },
  {
    'country': 'Bhutan',
    'region': 'Asia',
  },
  {
    'country': 'Bolivia',
    'region': 'South America',
  },
  {
    'country': 'Bonaire',
    'region': 'North America',
  },
  {
    'country': 'Bosnia and Herzegovina',
    'region': 'Europe',
  },
  {
    'country': 'Botswana',
    'region': 'Africa',
  },
  {
    'country': 'Bouvet Island',
    'region': 'Antarctica',
  },
  {
    'country': 'Brazil',
    'region': 'South America',
  },
  {
    'country': 'British Indian Ocean Territory',
    'region': 'Asia',
  },
  {
    'country': 'British Virgin Islands',
    'region': 'North America',
  },
  {
    'country': 'Brunei',
    'region': 'Asia',
  },
  {
    'country': 'Bulgaria',
    'region': 'Europe',
  },
  {
    'country': 'Burkina Faso',
    'region': 'Africa',
  },
  {
    'country': 'Burundi',
    'region': 'Africa',
  },
  {
    'country': 'Cambodia',
    'region': 'Asia',
  },
  {
    'country': 'Cameroon',
    'region': 'Africa',
  },
  {
    'country': 'Canada',
    'region': 'North America',
  },
  {
    'country': 'Cape Verde',
    'region': 'Africa',
  },
  {
    'country': 'Cayman Islands',
    'region': 'North America',
  },
  {
    'country': 'Central African Republic',
    'region': 'Africa',
  },
  {
    'country': 'Chad',
    'region': 'Africa',
  },
  {
    'country': 'Chile',
    'region': 'South America',
  },
  {
    'country': 'China',
    'region': 'Asia',
  },
  {
    'country': 'Christmas Island',
    'region': 'Asia',
  },
  {
    'country': 'Cocos [Keeling] Islands',
    'region': 'Asia',
  },
  {
    'country': 'Colombia',
    'region': 'South America',
  },
  {
    'country': 'Comoros',
    'region': 'Africa',
  },
  {
    'country': 'Cook Islands',
    'region': 'Oceania',
  },
  {
    'country': 'Costa Rica',
    'region': 'North America',
  },
  {
    'country': 'Croatia',
    'region': 'Europe',
  },
  {
    'country': 'Cuba',
    'region': 'North America',
  },
  {
    'country': 'Curacao',
    'region': 'North America',
  },
  {
    'country': 'Cyprus',
    'region': 'Europe',
  },
  {
    'country': 'Czechia',
    'region': 'Europe',
  },
  {
    'country': 'Democratic Republic of the Congo',
    'region': 'Africa',
  },
  {
    'country': 'Denmark',
    'region': 'Europe',
  },
  {
    'country': 'Djibouti',
    'region': 'Africa',
  },
  {
    'country': 'Dominica',
    'region': 'North America',
  },
  {
    'country': 'Dominican Republic',
    'region': 'North America',
  },
  {
    'country': 'East Timor',
    'region': 'Oceania',
  },
  {
    'country': 'Ecuador',
    'region': 'South America',
  },
  {
    'country': 'Egypt',
    'region': 'Africa',
  },
  {
    'country': 'El Salvador',
    'region': 'North America',
  },
  {
    'country': 'Equatorial Guinea',
    'region': 'Africa',
  },
  {
    'country': 'Eritrea',
    'region': 'Africa',
  },
  {
    'country': 'Estonia',
    'region': 'Europe',
  },
  {
    'country': 'Ethiopia',
    'region': 'Africa',
  },
  {
    'country': 'Falkland Islands',
    'region': 'South America',
  },
  {
    'country': 'Faroe Islands',
    'region': 'Europe',
  },
  {
    'country': 'Fiji',
    'region': 'Oceania',
  },
  {
    'country': 'Finland',
    'region': 'Europe',
  },
  {
    'country': 'France',
    'region': 'Europe',
  },
  {
    'country': 'French Guiana',
    'region': 'South America',
  },
  {
    'country': 'French Polynesia',
    'region': 'Oceania',
  },
  {
    'country': 'French Southern Territories',
    'region': 'Antarctica',
  },
  {
    'country': 'Gabon',
    'region': 'Africa',
  },
  {
    'country': 'Gambia',
    'region': 'Africa',
  },
  {
    'country': 'Georgia',
    'region': 'Asia',
  },
  {
    'country': 'Germany',
    'region': 'Europe',
  },
  {
    'country': 'Ghana',
    'region': 'Africa',
  },
  {
    'country': 'Gibraltar',
    'region': 'Europe',
  },
  {
    'country': 'Greece',
    'region': 'Europe',
  },
  {
    'country': 'Greenland',
    'region': 'North America',
  },
  {
    'country': 'Grenada',
    'region': 'North America',
  },
  {
    'country': 'Guadeloupe',
    'region': 'North America',
  },
  {
    'country': 'Guam',
    'region': 'Oceania',
  },
  {
    'country': 'Guatemala',
    'region': 'North America',
  },
  {
    'country': 'Guernsey',
    'region': 'Europe',
  },
  {
    'country': 'Guinea',
    'region': 'Africa',
  },
  {
    'country': 'Guinea-Bissau',
    'region': 'Africa',
  },
  {
    'country': 'Guyana',
    'region': 'South America',
  },
  {
    'country': 'Haiti',
    'region': 'North America',
  },
  {
    'country': 'Heard Island and McDonald Islands',
    'region': 'Antarctica',
  },
  {
    'country': 'Honduras',
    'region': 'North America',
  },
  {
    'country': 'Hong Kong',
    'region': 'Asia',
  },
  {
    'country': 'Hungary',
    'region': 'Europe',
  },
  {
    'country': 'Iceland',
    'region': 'Europe',
  },
  {
    'country': 'India',
    'region': 'Asia',
  },
  {
    'country': 'Indonesia',
    'region': 'Asia',
  },
  {
    'country': 'Iran',
    'region': 'Asia',
  },
  {
    'country': 'Iraq',
    'region': 'Asia',
  },
  {
    'country': 'Ireland',
    'region': 'Europe',
  },
  {
    'country': 'Isle of Man',
    'region': 'Europe',
  },
  {
    'country': 'Israel',
    'region': 'Asia',
  },
  {
    'country': 'Italy',
    'region': 'Europe',
  },
  {
    'country': 'Ivory Coast',
    'region': 'Africa',
  },
  {
    'country': 'Jamaica',
    'region': 'North America',
  },
  {
    'country': 'Japan',
    'region': 'Asia',
  },
  {
    'country': 'Jersey',
    'region': 'Europe',
  },
  {
    'country': 'Jordan',
    'region': 'Asia',
  },
  {
    'country': 'Kazakhstan',
    'region': 'Asia',
  },
  {
    'country': 'Kenya',
    'region': 'Africa',
  },
  {
    'country': 'Kiribati',
    'region': 'Oceania',
  },
  {
    'country': 'Kosovo',
    'region': 'Europe',
  },
  {
    'country': 'Kuwait',
    'region': 'Asia',
  },
  {
    'country': 'Kyrgyzstan',
    'region': 'Asia',
  },
  {
    'country': 'Laos',
    'region': 'Asia',
  },
  {
    'country': 'Latvia',
    'region': 'Europe',
  },
  {
    'country': 'Lebanon',
    'region': 'Asia',
  },
  {
    'country': 'Lesotho',
    'region': 'Africa',
  },
  {
    'country': 'Liberia',
    'region': 'Africa',
  },
  {
    'country': 'Libya',
    'region': 'Africa',
  },
  {
    'country': 'Liechtenstein',
    'region': 'Europe',
  },
  {
    'country': 'Lithuania',
    'region': 'Europe',
  },
  {
    'country': 'Luxembourg',
    'region': 'Europe',
  },
  {
    'country': 'Macao',
    'region': 'Asia',
  },
  {
    'country': 'Macedonia',
    'region': 'Europe',
  },
  {
    'country': 'Madagascar',
    'region': 'Africa',
  },
  {
    'country': 'Malawi',
    'region': 'Africa',
  },
  {
    'country': 'Malaysia',
    'region': 'Asia',
  },
  {
    'country': 'Maldives',
    'region': 'Asia',
  },
  {
    'country': 'Mali',
    'region': 'Africa',
  },
  {
    'country': 'Malta',
    'region': 'Europe',
  },
  {
    'country': 'Marshall Islands',
    'region': 'Oceania',
  },
  {
    'country': 'Martinique',
    'region': 'North America',
  },
  {
    'country': 'Mauritania',
    'region': 'Africa',
  },
  {
    'country': 'Mauritius',
    'region': 'Africa',
  },
  {
    'country': 'Mayotte',
    'region': 'Africa',
  },
  {
    'country': 'Mexico',
    'region': 'North America',
  },
  {
    'country': 'Micronesia',
    'region': 'Oceania',
  },
  {
    'country': 'Moldova',
    'region': 'Europe',
  },
  {
    'country': 'Monaco',
    'region': 'Europe',
  },
  {
    'country': 'Mongolia',
    'region': 'Asia',
  },
  {
    'country': 'Montenegro',
    'region': 'Europe',
  },
  {
    'country': 'Montserrat',
    'region': 'North America',
  },
  {
    'country': 'Morocco',
    'region': 'Africa',
  },
  {
    'country': 'Mozambique',
    'region': 'Africa',
  },
  {
    'country': 'Myanmar [Burma]',
    'region': 'Asia',
  },
  {
    'country': 'Namibia',
    'region': 'Africa',
  },
  {
    'country': 'Nauru',
    'region': 'Oceania',
  },
  {
    'country': 'Nepal',
    'region': 'Asia',
  },
  {
    'country': 'Netherlands',
    'region': 'Europe',
  },
  {
    'country': 'New Caledonia',
    'region': 'Oceania',
  },
  {
    'country': 'New Zealand',
    'region': 'Oceania',
  },
  {
    'country': 'Nicaragua',
    'region': 'North America',
  },
  {
    'country': 'Niger',
    'region': 'Africa',
  },
  {
    'country': 'Nigeria',
    'region': 'Africa',
  },
  {
    'country': 'Niue',
    'region': 'Oceania',
  },
  {
    'country': 'Norfolk Island',
    'region': 'Oceania',
  },
  {
    'country': 'North Korea',
    'region': 'Asia',
  },
  {
    'country': 'Northern Mariana Islands',
    'region': 'Oceania',
  },
  {
    'country': 'Norway',
    'region': 'Europe',
  },
  {
    'country': 'Oman',
    'region': 'Asia',
  },
  {
    'country': 'Pakistan',
    'region': 'Asia',
  },
  {
    'country': 'Palau',
    'region': 'Oceania',
  },
  {
    'country': 'Palestine',
    'region': 'Asia',
  },
  {
    'country': 'Panama',
    'region': 'North America',
  },
  {
    'country': 'Papua New Guinea',
    'region': 'Oceania',
  },
  {
    'country': 'Paraguay',
    'region': 'South America',
  },
  {
    'country': 'Peru',
    'region': 'South America',
  },
  {
    'country': 'Philippines',
    'region': 'Asia',
  },
  {
    'country': 'Pitcairn Islands',
    'region': 'Oceania',
  },
  {
    'country': 'Poland',
    'region': 'Europe',
  },
  {
    'country': 'Portugal',
    'region': 'Europe',
  },
  {
    'country': 'Puerto Rico',
    'region': 'North America',
  },
  {
    'country': 'Qatar',
    'region': 'Asia',
  },
  {
    'country': 'Republic of the Congo',
    'region': 'Africa',
  },
  {
    'country': 'Réunion',
    'region': 'Africa',
  },
  {
    'country': 'Romania',
    'region': 'Europe',
  },
  {
    'country': 'Russia',
    'region': 'Europe',
  },
  {
    'country': 'Rwanda',
    'region': 'Africa',
  },
  {
    'country': 'Saint Barthélemy',
    'region': 'North America',
  },
  {
    'country': 'Saint Helena',
    'region': 'Africa',
  },
  {
    'country': 'Saint Kitts and Nevis',
    'region': 'North America',
  },
  {
    'country': 'Saint Lucia',
    'region': 'North America',
  },
  {
    'country': 'Saint Martin',
    'region': 'North America',
  },
  {
    'country': 'Saint Pierre and Miquelon',
    'region': 'North America',
  },
  {
    'country': 'Saint Vincent and the Grenadines',
    'region': 'North America',
  },
  {
    'country': 'Samoa',
    'region': 'Oceania',
  },
  {
    'country': 'San Marino',
    'region': 'Europe',
  },
  {
    'country': 'São Tomé and Príncipe',
    'region': 'Africa',
  },
  {
    'country': 'Saudi Arabia',
    'region': 'Asia',
  },
  {
    'country': 'Senegal',
    'region': 'Africa',
  },
  {
    'country': 'Serbia',
    'region': 'Europe',
  },
  {
    'country': 'Seychelles',
    'region': 'Africa',
  },
  {
    'country': 'Sierra Leone',
    'region': 'Africa',
  },
  {
    'country': 'Singapore',
    'region': 'Asia',
  },
  {
    'country': 'Sint Maarten',
    'region': 'North America',
  },
  {
    'country': 'Slovakia',
    'region': 'Europe',
  },
  {
    'country': 'Slovenia',
    'region': 'Europe',
  },
  {
    'country': 'Solomon Islands',
    'region': 'Oceania',
  },
  {
    'country': 'Somalia',
    'region': 'Africa',
  },
  {
    'country': 'South Africa',
    'region': 'Africa',
  },
  {
    'country': 'South Georgia and the South Sandwich Islands',
    'region': 'Antarctica',
  },
  {
    'country': 'South Korea',
    'region': 'Asia',
  },
  {
    'country': 'South Sudan',
    'region': 'Africa',
  },
  {
    'country': 'Spain',
    'region': 'Europe',
  },
  {
    'country': 'Sri Lanka',
    'region': 'Asia',
  },
  {
    'country': 'Sudan',
    'region': 'Africa',
  },
  {
    'country': 'Suriname',
    'region': 'South America',
  },
  {
    'country': 'Svalbard and Jan Mayen',
    'region': 'Europe',
  },
  {
    'country': 'Swaziland',
    'region': 'Africa',
  },
  {
    'country': 'Sweden',
    'region': 'Europe',
  },
  {
    'country': 'Switzerland',
    'region': 'Europe',
  },
  {
    'country': 'Syria',
    'region': 'Asia',
  },
  {
    'country': 'Taiwan',
    'region': 'Asia',
  },
  {
    'country': 'Tajikistan',
    'region': 'Asia',
  },
  {
    'country': 'Tanzania',
    'region': 'Africa',
  },
  {
    'country': 'Thailand',
    'region': 'Asia',
  },
  {
    'country': 'Togo',
    'region': 'Africa',
  },
  {
    'country': 'Tokelau',
    'region': 'Oceania',
  },
  {
    'country': 'Tonga',
    'region': 'Oceania',
  },
  {
    'country': 'Trinidad and Tobago',
    'region': 'North America',
  },
  {
    'country': 'Tunisia',
    'region': 'Africa',
  },
  {
    'country': 'Turkey',
    'region': 'Asia',
  },
  {
    'country': 'Turkmenistan',
    'region': 'Asia',
  },
  {
    'country': 'Turks and Caicos Islands',
    'region': 'North America',
  },
  {
    'country': 'Tuvalu',
    'region': 'Oceania',
  },
  {
    'country': 'U.S. Minor Outlying Islands',
    'region': 'Oceania',
  },
  {
    'country': 'U.S. Virgin Islands',
    'region': 'North America',
  },
  {
    'country': 'Uganda',
    'region': 'Africa',
  },
  {
    'country': 'Ukraine',
    'region': 'Europe',
  },
  {
    'country': 'United Arab Emirates',
    'region': 'Asia',
  },
  {
    'country': 'United Kingdom',
    'region': 'Europe',
  },
  {
    'country': 'United States',
    'region': 'North America',
  },
  {
    'country': 'Uruguay',
    'region': 'South America',
  },
  {
    'country': 'Uzbekistan',
    'region': 'Asia',
  },
  {
    'country': 'Vanuatu',
    'region': 'Oceania',
  },
  {
    'country': 'Vatican City',
    'region': 'Europe',
  },
  {
    'country': 'Venezuela',
    'region': 'South America',
  },
  {
    'country': 'Vietnam',
    'region': 'Asia',
  },
  {
    'country': 'Wallis and Futuna',
    'region': 'Oceania',
  },
  {
    'country': 'Western Sahara',
    'region': 'Africa',
  },
  {
    'country': 'Yemen',
    'region': 'Asia',
  },
  {
    'country': 'Zambia',
    'region': 'Africa',
  },
  {
    'country': 'Zimbabwe',
    'region': 'Africa',
  },
];

const countries = () => countriesArray().map(item => item.country);

const countriesForReactSelect = () => countries().map((item) => ({ value: item, label: item }));


const roles = () => rolesArray().map(item => item.role);

const rolesForReactSelect = () => roles().map((item) => ({ value: item, label: item }));


const languagesForReactSelect = () => languages().map((item) => ({ value: item, label: item }));

const getRegion = (country) => countriesArray().find(item => item.country === country);


const getRoleDescription = (roleName) => rolesArray().find(item => item.role === roleName);


export {
  countries,
  skills,
  availableOptions,
  englishLevels,
  languages,
  roles,
  getRegion,
  getRoleDescription,
  countriesForReactSelect,
  rolesForReactSelect,
  languagesForReactSelect,
};
